In [2]:
import numpy as np

x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
   arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
arr=np.arange(0,9)
arr=arr.reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
x=[1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

In [15]:
nums=np.array ([1,2,0,0,4,0])
print(nums)
nonzeros = np.where(nums!=0)[0]
print(nonzeros)

[1 2 0 0 4 0]
[0 1 4]


In [23]:
arr=np.random.rand(10,10)
min=arr.min()
max=arr.max()
print('min value : ',min)
print('max value : ',max)


min value :  0.0110710218304787
max value :  0.9866697294964059


In [27]:
z=np.random.rand(30)
mean=z.mean()
print('mean is:',mean)

mean is: 0.41244850785946696
